---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-quota
  namespace: pro-security
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi